profiles:
- led_color: '000000'
  led_effect: Cycle
  led_duration: 4
  report_rate: Hz1000
  dpi_shift: 0
  dpi_default: 1
  dpis:
  - 1200
  - 0
  - 0
  - 0
  buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - modifiers:
    - Shift
    key: B
  - action: ProfileCycle
  - key: _1
  - key: _2
  - key: _3
  - key: _4
  - key: _5
  - key: _6
  - key: _7
  - key: _8
  - key: _9
  - key: _0
  - key: Minus
  - key: Equal
  g_led_color: '000000'
  g_buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - action: DPICycle
  - action: ProfileCycle
  - modifiers:
    - Ctrl
    key: _1
  - modifiers:
    - Ctrl
    key: _2
  - modifiers:
    - Ctrl
    key: _3
  - modifiers:
    - Ctrl
    key: _4
  - modifiers:
    - Ctrl
    key: _5
  - modifiers:
    - Ctrl
    key: _6
  - modifiers:
    - Ctrl
    key: _7
  - modifiers:
    - Ctrl
    key: _8
  - modifiers:
    - Ctrl
    key: _9
  - modifiers:
    - Ctrl
    key: _0
  - modifiers:
    - Ctrl
    key: Minus
  - modifiers:
    - Ctrl
    key: Equal
- led_color: FFFFFF
  led_effect: Solid
  led_duration: 11
  report_rate: Hz1000
  dpi_shift: 0
  dpi_default: 1
  dpis:
  - 1200
  - 0
  - 0
  - 0
  buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - modifiers:
    - Shift
    key: B
  - action: ProfileCycle
  - key: KP1
  - key: KP2
  - key: KP3
  - key: KP4
  - key: KP5
  - key: KP6
  - key: KP7
  - key: KP8
  - key: KP9
  - key: KP0
  - key: KPMinus
  - key: KPPlus
  g_led_color: FFFFFF
  g_buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - action: DPICycle
  - action: ProfileCycle
  - modifiers:
    - Ctrl
    key: _1
  - modifiers:
    - Ctrl
    key: _2
  - modifiers:
    - Ctrl
    key: _3
  - modifiers:
    - Ctrl
    key: _4
  - modifiers:
    - Ctrl
    key: _5
  - modifiers:
    - Ctrl
    key: _6
  - modifiers:
    - Ctrl
    key: _7
  - modifiers:
    - Ctrl
    key: _8
  - modifiers:
    - Ctrl
    key: _9
  - modifiers:
    - Ctrl
    key: _0
  - modifiers:
    - Ctrl
    key: Minus
  - modifiers:
    - Ctrl
    key: Equal
- led_color: 00FF00
  led_effect: Breath
  led_duration: 11
  report_rate: Hz1000
  dpi_shift: 400
  dpi_default: 2
  dpis:
  - 400
  - 1200
  - 2000
  - 3200
  buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: DPIShift
  - action: DPICycle
  - action: ProfileCycle
  - key: _1
  - key: _2
  - key: _3
  - key: _4
  - key: _5
  - key: _6
  - action: DPIUp
  - action: DPIDefault
  - action: WheelRight
  - action: DPIDown
  - key: E
  - action: WheelLeft
  g_led_color: 00FF00
  g_buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - action: DPICycle
  - action: ProfileCycle
  - modifiers:
    - Ctrl
    key: _1
  - modifiers:
    - Ctrl
    key: _2
  - modifiers:
    - Ctrl
    key: _3
  - modifiers:
    - Ctrl
    key: _4
  - modifiers:
    - Ctrl
    key: _5
  - modifiers:
    - Ctrl
    key: _6
  - modifiers:
    - Ctrl
    key: _7
  - modifiers:
    - Ctrl
    key: _8
  - modifiers:
    - Ctrl
    key: _9
  - modifiers:
    - Ctrl
    key: _0
  - modifiers:
    - Ctrl
    key: Minus
  - modifiers:
    - Ctrl
    key: Equal
