profiles:
- led_color: '000000'
  led_effect: Cycle
  led_duration: 4
  report_rate: Hz1000
  dpi_shift: 0
  dpi_default: 1
  dpis:
  - 800
  - 1200
  - 1600
  - 3200
  buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - action: DPICycle
  - action: ProfileCycle
  - key: _1
  - key: _2
  - key: _3
  - key: _4
  - key: _5
  - key: _6
  - key: _7
  - key: _8
  - key: _9
  - key: _0
  - key: Minus
  - key: Equal
  g_led_color: '000000'
  g_buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - action: DPICycle
  - action: ProfileCycle
  - modifiers:
    - Ctrl
    key: _1
  - modifiers:
    - Ctrl
    key: _2
  - modifiers:
    - Ctrl
    key: _3
  - modifiers:
    - Ctrl
    key: _4
  - modifiers:
    - Ctrl
    key: _5
  - modifiers:
    - Ctrl
    key: _6
  - modifiers:
    - Ctrl
    key: _7
  - modifiers:
    - Ctrl
    key: _8
  - modifiers:
    - Ctrl
    key: _9
  - modifiers:
    - Ctrl
    key: _0
  - modifiers:
    - Ctrl
    key: Minus
  - modifiers:
    - Ctrl
    key: Equal
- led_color: '000000'
  led_effect: Cycle
  led_duration: 4
  report_rate: Hz1000
  dpi_shift: 0
  dpi_default: 1
  dpis:
  - 800
  - 1200
  - 1600
  - 3200
  buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - action: DPICycle
  - action: ProfileCycle
  - key: _1
  - key: _2
  - key: _3
  - key: _4
  - key: _5
  - key: _6
  - key: _7
  - key: _8
  - key: _9
  - key: _0
  - key: Minus
  - key: Equal
  g_led_color: '000000'
  g_buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - action: DPICycle
  - action: ProfileCycle
  - modifiers:
    - Ctrl
    key: _1
  - modifiers:
    - Ctrl
    key: _2
  - modifiers:
    - Ctrl
    key: _3
  - modifiers:
    - Ctrl
    key: _4
  - modifiers:
    - Ctrl
    key: _5
  - modifiers:
    - Ctrl
    key: _6
  - modifiers:
    - Ctrl
    key: _7
  - modifiers:
    - Ctrl
    key: _8
  - modifiers:
    - Ctrl
    key: _9
  - modifiers:
    - Ctrl
    key: _0
  - modifiers:
    - Ctrl
    key: Minus
  - modifiers:
    - Ctrl
    key: Equal
- led_color: '000000'
  led_effect: Cycle
  led_duration: 4
  report_rate: Hz1000
  dpi_shift: 0
  dpi_default: 1
  dpis:
  - 800
  - 1200
  - 1600
  - 3200
  buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - action: DPICycle
  - action: ProfileCycle
  - key: _1
  - key: _2
  - key: _3
  - key: _4
  - key: _5
  - key: _6
  - key: _7
  - key: _8
  - key: _9
  - key: _0
  - key: Minus
  - key: Equal
  g_led_color: '000000'
  g_buttons:
  - action: LeftClick
  - action: RightClick
  - action: WheelClick
  - action: WheelLeft
  - action: WheelRight
  - action: GShift
  - action: DPICycle
  - action: ProfileCycle
  - modifiers:
    - Ctrl
    key: _1
  - modifiers:
    - Ctrl
    key: _2
  - modifiers:
    - Ctrl
    key: _3
  - modifiers:
    - Ctrl
    key: _4
  - modifiers:
    - Ctrl
    key: _5
  - modifiers:
    - Ctrl
    key: _6
  - modifiers:
    - Ctrl
    key: _7
  - modifiers:
    - Ctrl
    key: _8
  - modifiers:
    - Ctrl
    key: _9
  - modifiers:
    - Ctrl
    key: _0
  - modifiers:
    - Ctrl
    key: Minus
  - modifiers:
    - Ctrl
    key: Equal
